AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation template to create an S3 bucket

Parameters:
  BucketName:
    Description: A unique name for the S3 bucket
    Type: String
    Default: threeflow-test-devops-bucket

Resources:
  DevS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: Dev
        - Key: Purpose
          Value: Demo