name: Deploy CloudFormation to Dev

on:
  push:
    branches: [ '*' ]

permissions:
  id-token: write     # 👈 REQUIRED for OIDC
  contents: read 

jobs:
  deploy-cloudformation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials from OIDC role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::316119392696:role/GHA-dev-deployment-role
        aws-region: us-west-2

    - name: Deploy CloudFormation stack
      run: |
        for template in cloudformation/*.yaml; do
        stack_name=$(basename "$template" .yaml)-dev-stack

        echo "Deploying $stack_name using $template..."

        aws cloudformation deploy \
            --template-file "$template" \
            --stack-name "$stack_name" \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides Environment=dev
        done
        